blank_issues_enabled: true
contact_links:
  - name: Feature Request
    url: https://github.com/pairsys/goodmem/discussions/new?category=ideas
    about: Suggest a new feature or enhancement
  - name: Documentation Issue
    url: https://github.com/pairsys/goodmem/issues/new?labels=documentation
    about: Report issues with documentation
  - name: Discussion
    url: https://github.com/pairsys/goodmem/discussions/new
    about: Start a discussion about GoodMem