name: Code Quality Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: read

jobs:
  java-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          
      - name: Cache Google Java Format
        uses: actions/cache@v4
        with:
          path: .tools
          key: ${{ runner.os }}-gjf-1.21.0
          
      - name: Check Java Formatting
        id: format-check
        continue-on-error: true
        run: |
          ./server/format_java.sh --check server/src
          
      - name: Report formatting issues
        if: steps.format-check.outcome == 'failure'
        run: |
          echo "::warning::Java formatting check failed. Please run './server/format_java.sh --fix server/src' locally and commit the changes."

  go-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.2'
        
      - name: Run Go linting
        uses: golangci/golangci-lint-action@v7
        with:
          version: latest
          working-directory: cli
          args: --timeout=5m
          
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        if: github.event_name == 'pull_request'