name: Dependency Check

on:
  schedule:
    - cron: '0 0 * * 1'  # Run weekly on Mondays
  workflow_dispatch:      # Allow manual triggering

permissions:
  contents: read
  issues: write

jobs:
  check-java-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle
          
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v3
          
      - name: Check for outdated dependencies
        id: dependency-check
        run: |
          ./server/check_outdated.sh | tee dependency-report.txt
          
      - name: Create issue for outdated dependencies
        if: success()
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPORT_CONTENT: ${{ steps.dependency-check.outputs.stdout }}
        with:
          filename: .github/ISSUE_TEMPLATE/outdated-dependencies.md
          update_existing: true
          search_existing: open

  check-go-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.2'
          
      - name: Install go-mod-outdated
        run: go install github.com/psampaz/go-mod-outdated@latest
        
      - name: Check for outdated Go dependencies
        id: go-outdated
        run: |
          cd cli
          go list -u -m -json all | go-mod-outdated -update -direct | tee go-dependency-report.txt
          
      - name: Create issue for outdated Go dependencies
        if: success()
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPORT_CONTENT: ${{ steps.go-outdated.outputs.stdout }}
        with:
          filename: .github/ISSUE_TEMPLATE/outdated-go-dependencies.md
          update_existing: true
          search_existing: open